In [1]:
import numpy as np
import pandas as pd 
from matplotlib import pyplot as plt
import seaborn as sns
import os

In [2]:
pd.set_option('display.max_columns', None)
data = pd.read_csv('data.csv', sep = '\t', delimiter = None)

data.head()

,Q1A,Q1I,Q1E,Q2A,Q2I,Q2E,Q3A,Q3I,Q3E,Q4A,Q4I,Q4E,Q5A,Q5I,Q5E,Q6A,Q6I,Q6E,Q7A,Q7I,Q7E,Q8A,Q8I,Q8E,Q9A,Q9I,Q9E,Q10A,Q10I,Q10E,Q11A,Q11I,Q11E,Q12A,Q12I,Q12E,Q13A,Q13I,Q13E,Q14A,Q14I,Q14E,Q15A,Q15I,Q15E,Q16A,Q16I,Q16E,Q17A,Q17I,Q17E,Q18A,Q18I,Q18E,Q19A,Q19I,Q19E,Q20A,Q20I,Q20E,Q21A,Q21I,Q21E,Q22A,Q22I,Q22E,Q23A,Q23I,Q23E,Q24A,Q24I,Q24E,Q25A,Q25I,Q25E,Q26A,Q26I,Q26E,Q27A,Q27I,Q27E,Q28A,Q28I,Q28E,Q29A,Q29I,Q29E,Q30A,Q30I,Q30E,Q31A,Q31I,Q31E,Q32A,Q32I,Q32E,Q33A,Q33I,Q33E,Q34A,Q34I,Q34E,Q35A,Q35I,Q35E,Q36A,Q36I,Q36E,Q37A,Q37I,Q37E,Q38A,Q38I,Q38E,Q39A,Q39I,Q39E,Q40A,Q40I,Q40E,Q41A,Q41I,Q41E,Q42A,Q42I,Q42E,country,source,introelapse,testelapse,surveyelapse,TIPI1,TIPI2,TIPI3,TIPI4,TIPI5,TIPI6,TIPI7,TIPI8,TIPI9,TIPI10,VCL1,VCL2,VCL3,VCL4,VCL5,VCL6,VCL7,VCL8,VCL9,VCL10,VCL11,VCL12,VCL13,VCL14,VCL15,VCL16,education,urban,gender,engnat,age,screensize,uniquenetworklocation,hand,religion,orientation,race,voted,married,familysize,major
0,4,28,3890,4,25,2122,2,16,1944,4,8,2044,4,34,2153,4,33,2416,4,10,2818,4,13,2259,2,21,5541,1,38,4441,4,31,2451,4,24,3325,4,14,1416,4,37,5021,4,27,2342,4,39,2480,3,6,2476,4,35,1627,3,17,9050,3,30,7001,1,11,4719,4,20,2984,4,36,1313,4,42,2444,4,1,9880,4,2,4695,4,5,1677,3,4,6723,4,3,5953,2,26,8062,4,12,5560,4,7,3032,2,29,3316,3,40,3563,4,23,5594,4,41,1477,1,18,3885,2,9,5265,4,19,1892,3,22,4228,4,32,1574,4,15,2969,IN,2,19,167,166,1,5,7,7,7,7,7,5,1,1,1,0,0,1,1,0,1,0,0,1,0,0,0,1,1,1,2,3,2,2,16,1,1,1,12,1,10,2,1,2,NaN
1,4,2,8118,1,36,2890,2,35,4777,3,28,3090,4,10,5078,4,40,2790,3,18,3408,4,1,8342,3,37,916,2,32,1537,2,21,3926,2,25,3691,4,26,2004,4,4,8888,3,27,4109,3,19,4058,4,12,3692,2,6,3373,1,23,6015,1,16,3023,2,22,2670,3,3,5727,1,39,3641,2,33,2670,2,7,7649,3,11,2537,3,5,2907,4,9,1685,3,41,4726,3,17,6063,2,20,3307,3,14,4995,3,38,2505,2,34,2540,2,31,4359,3,15,3925,4,13,4609,2,30,3755,2,42,2323,1,24,5713,2,8,1334,2,29,5562,US,2,1,193,186,6,5,4,7,5,4,7,7,1,5,1,1,0,1,1,0,0,0,0,1,0,0,0,1,1,1,2,3,2,1,16,2,1,2,7,0,70,2,1,4,NaN
2,3,7,5784,1,33,4373,4,41,3242,1,13,6470,4,11,3927,3,9,3704,1,17,4550,3,5,3021,2,32,5864,4,21,3722,2,10,3424,1,36,3236,4,23,2489,1,34,7290,4,12,6587,4,22,3627,4,38,2905,2,18,2998,2,8,10233,1,16,4258,4,28,2888,3,4,59592,2,3,11732,4,2,8834,2,29,7358,1,30,4928,2,15,3036,1,19,4127,2,37,3934,2,26,10782,4,1,8273,3,39,3501,1,27,3824,4,25,2141,3,6,17461,4,24,1557,4,40,4446,4,42,1883,2,35,5790,2,14,4432,1,20,2203,4,31,5768,PL,2,5,271,122,2,5,2,2,5,6,5,5,3,2,1,0,0,1,1,0,0,0,0,0,1,0,0,1,1,1,2,3,2,2,17,2,1,1,4,3,60,1,1,3,NaN
3,2,23,5081,3,11,6837,2,37,5521,1,27,4556,3,28,3269,3,26,3231,4,2,7138,2,19,3079,3,31,9650,3,17,4179,2,5,5928,1,21,2838,1,20,2560,4,29,5139,2,22,3597,2,35,3336,3,10,4506,1,14,2695,1,25,8128,2,15,3125,1,6,4061,1,40,4272,1,12,4029,1,9,5630,1,18,30631,2,24,9870,4,4,2411,1,16,9478,3,1,7618,3,32,12639,3,34,5378,1,41,8923,2,38,2977,4,3,5620,1,7,16760,1,8,6427,2,39,3760,1,13,4112,3,42,2769,4,33,4432,4,30,3643,2,36,3698,US,2,3,261,336,1,1,7,4,6,4,6,1,6,1,1,0,0,1,1,0,0,0,0,1,0,0,0,1,1,1,1,3,2,1,13,2,1,2,4,5,70,2,1,5,biology
4,2,36,3215,2,13,7731,3,5,4156,4,10,2802,4,2,5628,2,9,6522,4,34,2374,4,11,3054,4,7,2975,3,14,3524,2,33,3033,4,23,2132,4,17,1314,4,16,3181,4,26,2249,3,19,2623,4,35,3093,4,38,7098,4,37,1938,4,15,3502,3,32,4776,3,18,4463,4,4,2436,2,40,4047,4,31,3787,4,42,2102,2,1,12351,4,3,2410,2,22,5056,4,39,3343,3,27,3012,4,20,3520,4,8,1868,4,25,2536,3,24,3725,4,30,2130,3,29,3952,3,21,10694,3,41,3231,4,12,3604,4,28,1950,3,6,6265,MY,2,1766,164,157,2,5,3,6,5,5,5,6,3,3,1,1,0,1,1,0,0,1,0,1,0,0,1,1,1,1,3,2,2,2,19,2,2,3,10,1,10,2,1,4,Psychology

In [3]:
# duplicate data
data_1 = data.copy()
# Remove major
data_1 = data_1.drop(['major', 'country', 'uniquenetworklocation', 'source'],axis=1)
# Remove time and position
time = [i for i in data_1.iloc[:,0:126] if  'E' in i]
position = [i for i in data_1.iloc[:,0:126] if  'I' in i]
data_1 = data_1.drop(position,axis=1)
data_1 = data_1.drop(time,axis=1)
# remove introelapse, testelapse, surveyelapse
data_1 = data_1.drop(data_1.iloc[:,42:45],axis=1)
data_2 = data_1.copy()
# Remove VCL
# data_2 = data_2.drop(data_2.iloc[:,52:68],axis=1)
# data_2 = data_2.replace(to_replace=0,value=3)
# Rename Ten Item Personlaity code
data_2 = data_2.rename(columns={'TIPI1':'Extraverted-enthusiastic','TIPI2':'Critical-quarrelsome',
                            'TIPI3':'Dependable-self_disciplined','TIPI4':'Anxious-easily upset',
                            'TIPI5':'Open to new experiences-complex','TIPI6':'Reserved-quiet',
                            'TIPI7':'Sympathetic-warm','TIPI8':'Disorganized-careless','TIPI9':'Calm-emotionally_stable',
                            'TIPI10':'Conventional-uncreative'})
#print('Shape',data_1.shape)
#print('Attributes',data_1.columns)
print('Shape',data_2.shape)
print('Attributes',data_2.columns)

Shape (39775, 81)
Attributes Index(['Q1A', 'Q2A', 'Q3A', 'Q4A', 'Q5A', 'Q6A', 'Q7A', 'Q8A', 'Q9A', 'Q10A',
       'Q11A', 'Q12A', 'Q13A', 'Q14A', 'Q15A', 'Q16A', 'Q17A', 'Q18A', 'Q19A',
       'Q20A', 'Q21A', 'Q22A', 'Q23A', 'Q24A', 'Q25A', 'Q26A', 'Q27A', 'Q28A',
       'Q29A', 'Q30A', 'Q31A', 'Q32A', 'Q33A', 'Q34A', 'Q35A', 'Q36A', 'Q37A',
       'Q38A', 'Q39A', 'Q40A', 'Q41A', 'Q42A', 'Extraverted-enthusiastic',
       'Critical-quarrelsome', 'Dependable-self_disciplined',
       'Anxious-easily upset', 'Open to new experiences-complex',
       'Reserved-quiet', 'Sympathetic-warm', 'Disorganized-careless',
       'Calm-emotionally_stable', 'Conventional-uncreative', 'VCL1', 'VCL2',
       'VCL3', 'VCL4', 'VCL5', 'VCL6', 'VCL7', 'VCL8', 'VCL9', 'VCL10',
       'VCL11', 'VCL12', 'VCL13', 'VCL14', 'VCL15', 'VCL16', 'education',
       'urban', 'gender', 'engnat', 'age', 'screensize', 'hand', 'religion',
       'orientation', 'race', 'voted', 'married', 'familysize'],
      dtype='object')

In [4]:
pd.set_option('display.max_columns', None)
data_2.head()

,Q1A,Q2A,Q3A,Q4A,Q5A,Q6A,Q7A,Q8A,Q9A,Q10A,Q11A,Q12A,Q13A,Q14A,Q15A,Q16A,Q17A,Q18A,Q19A,Q20A,Q21A,Q22A,Q23A,Q24A,Q25A,Q26A,Q27A,Q28A,Q29A,Q30A,Q31A,Q32A,Q33A,Q34A,Q35A,Q36A,Q37A,Q38A,Q39A,Q40A,Q41A,Q42A,Extraverted-enthusiastic,Critical-quarrelsome,Dependable-self_disciplined,Anxious-easily upset,Open to new experiences-complex,Reserved-quiet,Sympathetic-warm,Disorganized-careless,Calm-emotionally_stable,Conventional-uncreative,VCL1,VCL2,VCL3,VCL4,VCL5,VCL6,VCL7,VCL8,VCL9,VCL10,VCL11,VCL12,VCL13,VCL14,VCL15,VCL16,education,urban,gender,engnat,age,screensize,hand,religion,orientation,race,voted,married,familysize
0,4,4,2,4,4,4,4,4,2,1,4,4,4,4,4,4,3,4,3,3,1,4,4,4,4,4,4,3,4,2,4,4,2,3,4,4,1,2,4,3,4,4,1,5,7,7,7,7,7,5,1,1,1,0,0,1,1,0,1,0,0,1,0,0,0,1,1,1,2,3,2,2,16,1,1,12,1,10,2,1,2
1,4,1,2,3,4,4,3,4,3,2,2,2,4,4,3,3,4,2,1,1,2,3,1,2,2,3,3,4,3,3,2,3,3,2,2,3,4,2,2,1,2,2,6,5,4,7,5,4,7,7,1,5,1,1,0,1,1,0,0,0,0,1,0,0,0,1,1,1,2,3,2,1,16,2,2,7,0,70,2,1,4
2,3,1,4,1,4,3,1,3,2,4,2,1,4,1,4,4,4,2,2,1,4,3,2,4,2,1,2,1,2,2,4,3,1,4,3,4,4,4,2,2,1,4,2,5,2,2,5,6,5,5,3,2,1,0,0,1,1,0,0,0,0,0,1,0,0,1,1,1,2,3,2,2,17,2,1,4,3,60,1,1,3
3,2,3,2,1,3,3,4,2,3,3,2,1,1,4,2,2,3,1,1,2,1,1,1,1,1,2,4,1,3,3,3,1,2,4,1,1,2,1,3,4,4,2,1,1,7,4,6,4,6,1,6,1,1,0,0,1,1,0,0,0,0,1,0,0,0,1,1,1,1,3,2,1,13,2,2,4,5,70,2,1,5
4,2,2,3,4,4,2,4,4,4,3,2,4,4,4,4,3,4,4,4,4,3,3,4,2,4,4,2,4,2,4,3,4,4,4,3,4,3,3,3,4,4,3,2,5,3,6,5,5,5,6,3,3,1,1,0,1,1,0,0,1,0,1,0,0,1,1,1,1,3,2,2,2,19,2,3,10,1,10,2,1,4

In [5]:
# Grouping age
def condition(x):
    if x <= 10:
        return 0 #'Under Age'
    if  10 <= x <= 16:
        return 1 #'Children'
    if 17 <= x <= 21:
        return 2 #'Teen'
    if 21 <= x <= 35:
        return 3 #'Adults'
    if 36 <= x <= 48:
        return 4 #'Elder Adults'
    if x >= 49:
        return 5 #'Older People'

data_2['AgeGroups'] = data_2['age'].apply(condition)
data_2.head()

,Q1A,Q2A,Q3A,Q4A,Q5A,Q6A,Q7A,Q8A,Q9A,Q10A,Q11A,Q12A,Q13A,Q14A,Q15A,Q16A,Q17A,Q18A,Q19A,Q20A,Q21A,Q22A,Q23A,Q24A,Q25A,Q26A,Q27A,Q28A,Q29A,Q30A,Q31A,Q32A,Q33A,Q34A,Q35A,Q36A,Q37A,Q38A,Q39A,Q40A,Q41A,Q42A,Extraverted-enthusiastic,Critical-quarrelsome,Dependable-self_disciplined,Anxious-easily upset,Open to new experiences-complex,Reserved-quiet,Sympathetic-warm,Disorganized-careless,Calm-emotionally_stable,Conventional-uncreative,VCL1,VCL2,VCL3,VCL4,VCL5,VCL6,VCL7,VCL8,VCL9,VCL10,VCL11,VCL12,VCL13,VCL14,VCL15,VCL16,education,urban,gender,engnat,age,screensize,hand,religion,orientation,race,voted,married,familysize,AgeGroups
0,4,4,2,4,4,4,4,4,2,1,4,4,4,4,4,4,3,4,3,3,1,4,4,4,4,4,4,3,4,2,4,4,2,3,4,4,1,2,4,3,4,4,1,5,7,7,7,7,7,5,1,1,1,0,0,1,1,0,1,0,0,1,0,0,0,1,1,1,2,3,2,2,16,1,1,12,1,10,2,1,2,1
1,4,1,2,3,4,4,3,4,3,2,2,2,4,4,3,3,4,2,1,1,2,3,1,2,2,3,3,4,3,3,2,3,3,2,2,3,4,2,2,1,2,2,6,5,4,7,5,4,7,7,1,5,1,1,0,1,1,0,0,0,0,1,0,0,0,1,1,1,2,3,2,1,16,2,2,7,0,70,2,1,4,1
2,3,1,4,1,4,3,1,3,2,4,2,1,4,1,4,4,4,2,2,1,4,3,2,4,2,1,2,1,2,2,4,3,1,4,3,4,4,4,2,2,1,4,2,5,2,2,5,6,5,5,3,2,1,0,0,1,1,0,0,0,0,0,1,0,0,1,1,1,2,3,2,2,17,2,1,4,3,60,1,1,3,2
3,2,3,2,1,3,3,4,2,3,3,2,1,1,4,2,2,3,1,1,2,1,1,1,1,1,2,4,1,3,3,3,1,2,4,1,1,2,1,3,4,4,2,1,1,7,4,6,4,6,1,6,1,1,0,0,1,1,0,0,0,0,1,0,0,0,1,1,1,1,3,2,1,13,2,2,4,5,70,2,1,5,1
4,2,2,3,4,4,2,4,4,4,3,2,4,4,4,4,3,4,4,4,4,3,3,4,2,4,4,2,4,2,4,3,4,4,4,3,4,3,3,3,4,4,3,2,5,3,6,5,5,5,6,3,3,1,1,0,1,1,0,0,1,0,1,0,0,1,1,1,1,3,2,2,2,19,2,3,10,1,10,2,1,4,2

In [6]:
# Filter DAS
data_das = data_2.iloc[:,42:]
#print('Attributes',data_das.columns)
data_3=data_2.filter(regex='Q\d{1,2}A')
#print('Attributes',data_3.columns)
data_3.head()

,Q1A,Q2A,Q3A,Q4A,Q5A,Q6A,Q7A,Q8A,Q9A,Q10A,Q11A,Q12A,Q13A,Q14A,Q15A,Q16A,Q17A,Q18A,Q19A,Q20A,Q21A,Q22A,Q23A,Q24A,Q25A,Q26A,Q27A,Q28A,Q29A,Q30A,Q31A,Q32A,Q33A,Q34A,Q35A,Q36A,Q37A,Q38A,Q39A,Q40A,Q41A,Q42A
0,4,4,2,4,4,4,4,4,2,1,4,4,4,4,4,4,3,4,3,3,1,4,4,4,4,4,4,3,4,2,4,4,2,3,4,4,1,2,4,3,4,4
1,4,1,2,3,4,4,3,4,3,2,2,2,4,4,3,3,4,2,1,1,2,3,1,2,2,3,3,4,3,3,2,3,3,2,2,3,4,2,2,1,2,2
2,3,1,4,1,4,3,1,3,2,4,2,1,4,1,4,4,4,2,2,1,4,3,2,4,2,1,2,1,2,2,4,3,1,4,3,4,4,4,2,2,1,4
3,2,3,2,1,3,3,4,2,3,3,2,1,1,4,2,2,3,1,1,2,1,1,1,1,1,2,4,1,3,3,3,1,2,4,1,1,2,1,3,4,4,2
4,2,2,3,4,4,2,4,4,4,3,2,4,4,4,4,3,4,4,4,4,3,3,4,2,4,4,2,4,2,4,3,4,4,4,3,4,3,3,3,4,4,3

In [7]:
# Categorized DAS
def sub(data_3):
    return data_3.subtract(1,axis=1)
data_3 = sub(data_3)
das_keys = {'Depression': [3, 5, 10, 13, 16, 17, 21, 24, 26, 31, 34, 37, 38, 42],
             'Anxiety': [2, 4, 7, 9, 15, 19, 20, 23, 25, 28, 30, 36, 40, 41],
             'Stress': [1, 6, 8, 11, 12, 14, 18, 22, 27, 29, 32, 33, 35, 39]}
d = []
for i in das_keys["Depression"]:
    d.append('Q'+str(i)+'A')
s = []
for i in das_keys["Stress"]:
    s.append('Q'+str(i)+'A')
a = []
for i in das_keys["Anxiety"]:
    a.append('Q'+str(i)+'A')
depression = data_3.filter(d)
stress = data_3.filter(s)
anxiety = data_3.filter(a)

In [8]:
# scoring system
def scores(source):
    col=list(source)
    source['Total_Count']=source[col].sum(axis=1)
    return source
depression=scores(depression)
stress=scores(stress)
anxiety=scores(anxiety)

display(depression.head(), stress.head(), anxiety.head())

,Q3A,Q5A,Q10A,Q13A,Q16A,Q17A,Q21A,Q24A,Q26A,Q31A,Q34A,Q37A,Q38A,Q42A,Total_Count
0,1,3,0,3,3,2,0,3,3,3,2,0,1,3,27
1,1,3,1,3,2,3,1,1,2,1,1,3,1,1,24
2,3,3,3,3,3,3,3,3,0,3,3,3,3,3,39
3,1,2,2,0,1,2,0,0,1,2,3,1,0,1,16
4,2,3,2,3,2,3,2,1,3,2,3,2,2,2,32

,Q1A,Q6A,Q8A,Q11A,Q12A,Q14A,Q18A,Q22A,Q27A,Q29A,Q32A,Q33A,Q35A,Q39A,Total_Count
0,3,3,3,3,3,3,3,3,3,3,3,1,3,3,40
1,3,3,3,1,1,3,1,2,2,2,2,2,1,1,27
2,2,2,2,1,0,0,1,2,1,1,2,0,2,1,17
3,1,2,1,1,0,3,0,0,3,2,0,1,0,2,16
4,1,1,3,1,3,3,3,2,1,1,3,3,2,2,29

,Q2A,Q4A,Q7A,Q9A,Q15A,Q19A,Q20A,Q23A,Q25A,Q28A,Q30A,Q36A,Q40A,Q41A,Total_Count
0,3,3,3,1,3,2,2,3,3,2,1,3,2,3,34
1,0,2,2,2,2,0,0,0,1,3,2,2,0,1,17
2,0,0,0,1,3,1,0,1,1,0,1,3,1,0,12
3,2,0,3,2,1,0,1,0,0,0,2,0,3,3,17
4,1,3,3,3,3,3,3,3,3,3,3,3,3,3,40

In [9]:
DEPRESSION = pd.merge(depression, data_das, how='inner', left_index=True, right_index=True)
ANXIETY = pd.merge(anxiety, data_das, how='inner', left_index=True, right_index=True)
STRESS = pd.merge(stress, data_das, how='inner', left_index=True, right_index=True)

# print('Attributes',DEPRESSION.columns)
display(DEPRESSION.head() , STRESS.head(), ANXIETY.head())

,Q3A,Q5A,Q10A,Q13A,Q16A,Q17A,Q21A,Q24A,Q26A,Q31A,Q34A,Q37A,Q38A,Q42A,Total_Count,Extraverted-enthusiastic,Critical-quarrelsome,Dependable-self_disciplined,Anxious-easily upset,Open to new experiences-complex,Reserved-quiet,Sympathetic-warm,Disorganized-careless,Calm-emotionally_stable,Conventional-uncreative,VCL1,VCL2,VCL3,VCL4,VCL5,VCL6,VCL7,VCL8,VCL9,VCL10,VCL11,VCL12,VCL13,VCL14,VCL15,VCL16,education,urban,gender,engnat,age,screensize,hand,religion,orientation,race,voted,married,familysize,AgeGroups
0,1,3,0,3,3,2,0,3,3,3,2,0,1,3,27,1,5,7,7,7,7,7,5,1,1,1,0,0,1,1,0,1,0,0,1,0,0,0,1,1,1,2,3,2,2,16,1,1,12,1,10,2,1,2,1
1,1,3,1,3,2,3,1,1,2,1,1,3,1,1,24,6,5,4,7,5,4,7,7,1,5,1,1,0,1,1,0,0,0,0,1,0,0,0,1,1,1,2,3,2,1,16,2,2,7,0,70,2,1,4,1
2,3,3,3,3,3,3,3,3,0,3,3,3,3,3,39,2,5,2,2,5,6,5,5,3,2,1,0,0,1,1,0,0,0,0,0,1,0,0,1,1,1,2,3,2,2,17,2,1,4,3,60,1,1,3,2
3,1,2,2,0,1,2,0,0,1,2,3,1,0,1,16,1,1,7,4,6,4,6,1,6,1,1,0,0,1,1,0,0,0,0,1,0,0,0,1,1,1,1,3,2,1,13,2,2,4,5,70,2,1,5,1
4,2,3,2,3,2,3,2,1,3,2,3,2,2,2,32,2,5,3,6,5,5,5,6,3,3,1,1,0,1,1,0,0,1,0,1,0,0,1,1,1,1,3,2,2,2,19,2,3,10,1,10,2,1,4,2

,Q1A,Q6A,Q8A,Q11A,Q12A,Q14A,Q18A,Q22A,Q27A,Q29A,Q32A,Q33A,Q35A,Q39A,Total_Count,Extraverted-enthusiastic,Critical-quarrelsome,Dependable-self_disciplined,Anxious-easily upset,Open to new experiences-complex,Reserved-quiet,Sympathetic-warm,Disorganized-careless,Calm-emotionally_stable,Conventional-uncreative,VCL1,VCL2,VCL3,VCL4,VCL5,VCL6,VCL7,VCL8,VCL9,VCL10,VCL11,VCL12,VCL13,VCL14,VCL15,VCL16,education,urban,gender,engnat,age,screensize,hand,religion,orientation,race,voted,married,familysize,AgeGroups
0,3,3,3,3,3,3,3,3,3,3,3,1,3,3,40,1,5,7,7,7,7,7,5,1,1,1,0,0,1,1,0,1,0,0,1,0,0,0,1,1,1,2,3,2,2,16,1,1,12,1,10,2,1,2,1
1,3,3,3,1,1,3,1,2,2,2,2,2,1,1,27,6,5,4,7,5,4,7,7,1,5,1,1,0,1,1,0,0,0,0,1,0,0,0,1,1,1,2,3,2,1,16,2,2,7,0,70,2,1,4,1
2,2,2,2,1,0,0,1,2,1,1,2,0,2,1,17,2,5,2,2,5,6,5,5,3,2,1,0,0,1,1,0,0,0,0,0,1,0,0,1,1,1,2,3,2,2,17,2,1,4,3,60,1,1,3,2
3,1,2,1,1,0,3,0,0,3,2,0,1,0,2,16,1,1,7,4,6,4,6,1,6,1,1,0,0,1,1,0,0,0,0,1,0,0,0,1,1,1,1,3,2,1,13,2,2,4,5,70,2,1,5,1
4,1,1,3,1,3,3,3,2,1,1,3,3,2,2,29,2,5,3,6,5,5,5,6,3,3,1,1,0,1,1,0,0,1,0,1,0,0,1,1,1,1,3,2,2,2,19,2,3,10,1,10,2,1,4,2

,Q2A,Q4A,Q7A,Q9A,Q15A,Q19A,Q20A,Q23A,Q25A,Q28A,Q30A,Q36A,Q40A,Q41A,Total_Count,Extraverted-enthusiastic,Critical-quarrelsome,Dependable-self_disciplined,Anxious-easily upset,Open to new experiences-complex,Reserved-quiet,Sympathetic-warm,Disorganized-careless,Calm-emotionally_stable,Conventional-uncreative,VCL1,VCL2,VCL3,VCL4,VCL5,VCL6,VCL7,VCL8,VCL9,VCL10,VCL11,VCL12,VCL13,VCL14,VCL15,VCL16,education,urban,gender,engnat,age,screensize,hand,religion,orientation,race,voted,married,familysize,AgeGroups
0,3,3,3,1,3,2,2,3,3,2,1,3,2,3,34,1,5,7,7,7,7,7,5,1,1,1,0,0,1,1,0,1,0,0,1,0,0,0,1,1,1,2,3,2,2,16,1,1,12,1,10,2,1,2,1
1,0,2,2,2,2,0,0,0,1,3,2,2,0,1,17,6,5,4,7,5,4,7,7,1,5,1,1,0,1,1,0,0,0,0,1,0,0,0,1,1,1,2,3,2,1,16,2,2,7,0,70,2,1,4,1
2,0,0,0,1,3,1,0,1,1,0,1,3,1,0,12,2,5,2,2,5,6,5,5,3,2,1,0,0,1,1,0,0,0,0,0,1,0,0,1,1,1,2,3,2,2,17,2,1,4,3,60,1,1,3,2
3,2,0,3,2,1,0,1,0,0,0,2,0,3,3,17,1,1,7,4,6,4,6,1,6,1,1,0,0,1,1,0,0,0,0,1,0,0,0,1,1,1,1,3,2,1,13,2,2,4,5,70,2,1,5,1
4,1,3,3,3,3,3,3,3,3,3,3,3,3,3,40,2,5,3,6,5,5,5,6,3,3,1,1,0,1,1,0,0,1,0,1,0,0,1,1,1,1,3,2,2,2,19,2,3,10,1,10,2,1,4,2

In [10]:
def depression_condition(x):
    if x <= 13:
        return 0 # normal
    if 14 <= x <= 20:
        return 1 # moderate
    if x >= 21:
        return 2 # severe

def anxiety_condition(x):
    if x <= 13:
        return 0 # normal
    if 14 <= x <= 20:
        return 1 # moderate
    if x >= 21:
        return 2 # severe

def stress_condition(x):
    if x <= 13:
        return 0 # normal
    if 14 <= x <= 20:
        return 1 # moderate
    if x >= 21:
        return 2 # severe

DEPRESSION['Condition'] = DEPRESSION['Total_Count'].apply(depression_condition)
ANXIETY['Condition'] = ANXIETY['Total_Count'].apply(anxiety_condition)
STRESS['Condition'] = STRESS['Total_Count'].apply(stress_condition)

display(DEPRESSION.head(), STRESS.head(), ANXIETY.head())

,Q3A,Q5A,Q10A,Q13A,Q16A,Q17A,Q21A,Q24A,Q26A,Q31A,Q34A,Q37A,Q38A,Q42A,Total_Count,Extraverted-enthusiastic,Critical-quarrelsome,Dependable-self_disciplined,Anxious-easily upset,Open to new experiences-complex,Reserved-quiet,Sympathetic-warm,Disorganized-careless,Calm-emotionally_stable,Conventional-uncreative,VCL1,VCL2,VCL3,VCL4,VCL5,VCL6,VCL7,VCL8,VCL9,VCL10,VCL11,VCL12,VCL13,VCL14,VCL15,VCL16,education,urban,gender,engnat,age,screensize,hand,religion,orientation,race,voted,married,familysize,AgeGroups,Condition
0,1,3,0,3,3,2,0,3,3,3,2,0,1,3,27,1,5,7,7,7,7,7,5,1,1,1,0,0,1,1,0,1,0,0,1,0,0,0,1,1,1,2,3,2,2,16,1,1,12,1,10,2,1,2,1,2
1,1,3,1,3,2,3,1,1,2,1,1,3,1,1,24,6,5,4,7,5,4,7,7,1,5,1,1,0,1,1,0,0,0,0,1,0,0,0,1,1,1,2,3,2,1,16,2,2,7,0,70,2,1,4,1,2
2,3,3,3,3,3,3,3,3,0,3,3,3,3,3,39,2,5,2,2,5,6,5,5,3,2,1,0,0,1,1,0,0,0,0,0,1,0,0,1,1,1,2,3,2,2,17,2,1,4,3,60,1,1,3,2,2
3,1,2,2,0,1,2,0,0,1,2,3,1,0,1,16,1,1,7,4,6,4,6,1,6,1,1,0,0,1,1,0,0,0,0,1,0,0,0,1,1,1,1,3,2,1,13,2,2,4,5,70,2,1,5,1,1
4,2,3,2,3,2,3,2,1,3,2,3,2,2,2,32,2,5,3,6,5,5,5,6,3,3,1,1,0,1,1,0,0,1,0,1,0,0,1,1,1,1,3,2,2,2,19,2,3,10,1,10,2,1,4,2,2

,Q1A,Q6A,Q8A,Q11A,Q12A,Q14A,Q18A,Q22A,Q27A,Q29A,Q32A,Q33A,Q35A,Q39A,Total_Count,Extraverted-enthusiastic,Critical-quarrelsome,Dependable-self_disciplined,Anxious-easily upset,Open to new experiences-complex,Reserved-quiet,Sympathetic-warm,Disorganized-careless,Calm-emotionally_stable,Conventional-uncreative,VCL1,VCL2,VCL3,VCL4,VCL5,VCL6,VCL7,VCL8,VCL9,VCL10,VCL11,VCL12,VCL13,VCL14,VCL15,VCL16,education,urban,gender,engnat,age,screensize,hand,religion,orientation,race,voted,married,familysize,AgeGroups,Condition
0,3,3,3,3,3,3,3,3,3,3,3,1,3,3,40,1,5,7,7,7,7,7,5,1,1,1,0,0,1,1,0,1,0,0,1,0,0,0,1,1,1,2,3,2,2,16,1,1,12,1,10,2,1,2,1,2
1,3,3,3,1,1,3,1,2,2,2,2,2,1,1,27,6,5,4,7,5,4,7,7,1,5,1,1,0,1,1,0,0,0,0,1,0,0,0,1,1,1,2,3,2,1,16,2,2,7,0,70,2,1,4,1,2
2,2,2,2,1,0,0,1,2,1,1,2,0,2,1,17,2,5,2,2,5,6,5,5,3,2,1,0,0,1,1,0,0,0,0,0,1,0,0,1,1,1,2,3,2,2,17,2,1,4,3,60,1,1,3,2,1
3,1,2,1,1,0,3,0,0,3,2,0,1,0,2,16,1,1,7,4,6,4,6,1,6,1,1,0,0,1,1,0,0,0,0,1,0,0,0,1,1,1,1,3,2,1,13,2,2,4,5,70,2,1,5,1,1
4,1,1,3,1,3,3,3,2,1,1,3,3,2,2,29,2,5,3,6,5,5,5,6,3,3,1,1,0,1,1,0,0,1,0,1,0,0,1,1,1,1,3,2,2,2,19,2,3,10,1,10,2,1,4,2,2

,Q2A,Q4A,Q7A,Q9A,Q15A,Q19A,Q20A,Q23A,Q25A,Q28A,Q30A,Q36A,Q40A,Q41A,Total_Count,Extraverted-enthusiastic,Critical-quarrelsome,Dependable-self_disciplined,Anxious-easily upset,Open to new experiences-complex,Reserved-quiet,Sympathetic-warm,Disorganized-careless,Calm-emotionally_stable,Conventional-uncreative,VCL1,VCL2,VCL3,VCL4,VCL5,VCL6,VCL7,VCL8,VCL9,VCL10,VCL11,VCL12,VCL13,VCL14,VCL15,VCL16,education,urban,gender,engnat,age,screensize,hand,religion,orientation,race,voted,married,familysize,AgeGroups,Condition
0,3,3,3,1,3,2,2,3,3,2,1,3,2,3,34,1,5,7,7,7,7,7,5,1,1,1,0,0,1,1,0,1,0,0,1,0,0,0,1,1,1,2,3,2,2,16,1,1,12,1,10,2,1,2,1,2
1,0,2,2,2,2,0,0,0,1,3,2,2,0,1,17,6,5,4,7,5,4,7,7,1,5,1,1,0,1,1,0,0,0,0,1,0,0,0,1,1,1,2,3,2,1,16,2,2,7,0,70,2,1,4,1,1
2,0,0,0,1,3,1,0,1,1,0,1,3,1,0,12,2,5,2,2,5,6,5,5,3,2,1,0,0,1,1,0,0,0,0,0,1,0,0,1,1,1,2,3,2,2,17,2,1,4,3,60,1,1,3,2,0
3,2,0,3,2,1,0,1,0,0,0,2,0,3,3,17,1,1,7,4,6,4,6,1,6,1,1,0,0,1,1,0,0,0,0,1,0,0,0,1,1,1,1,3,2,1,13,2,2,4,5,70,2,1,5,1,1
4,1,3,3,3,3,3,3,3,3,3,3,3,3,3,40,2,5,3,6,5,5,5,6,3,3,1,1,0,1,1,0,0,1,0,1,0,0,1,1,1,1,3,2,2,2,19,2,3,10,1,10,2,1,4,2,2

In [11]:
# Simplified variable
data_depression=DEPRESSION.copy()
data_anxiety=ANXIETY.copy()
data_stress=STRESS.copy()

data_depression = data_depression.drop(columns=['Total_Count'])
data_anxiety = data_anxiety.drop(columns=['Total_Count'])
data_stress = data_stress.drop(columns=['Total_Count'])

display(data_depression.head(), data_anxiety.head(), data_stress.head())

,Q3A,Q5A,Q10A,Q13A,Q16A,Q17A,Q21A,Q24A,Q26A,Q31A,Q34A,Q37A,Q38A,Q42A,Extraverted-enthusiastic,Critical-quarrelsome,Dependable-self_disciplined,Anxious-easily upset,Open to new experiences-complex,Reserved-quiet,Sympathetic-warm,Disorganized-careless,Calm-emotionally_stable,Conventional-uncreative,VCL1,VCL2,VCL3,VCL4,VCL5,VCL6,VCL7,VCL8,VCL9,VCL10,VCL11,VCL12,VCL13,VCL14,VCL15,VCL16,education,urban,gender,engnat,age,screensize,hand,religion,orientation,race,voted,married,familysize,AgeGroups,Condition
0,1,3,0,3,3,2,0,3,3,3,2,0,1,3,1,5,7,7,7,7,7,5,1,1,1,0,0,1,1,0,1,0,0,1,0,0,0,1,1,1,2,3,2,2,16,1,1,12,1,10,2,1,2,1,2
1,1,3,1,3,2,3,1,1,2,1,1,3,1,1,6,5,4,7,5,4,7,7,1,5,1,1,0,1,1,0,0,0,0,1,0,0,0,1,1,1,2,3,2,1,16,2,2,7,0,70,2,1,4,1,2
2,3,3,3,3,3,3,3,3,0,3,3,3,3,3,2,5,2,2,5,6,5,5,3,2,1,0,0,1,1,0,0,0,0,0,1,0,0,1,1,1,2,3,2,2,17,2,1,4,3,60,1,1,3,2,2
3,1,2,2,0,1,2,0,0,1,2,3,1,0,1,1,1,7,4,6,4,6,1,6,1,1,0,0,1,1,0,0,0,0,1,0,0,0,1,1,1,1,3,2,1,13,2,2,4,5,70,2,1,5,1,1
4,2,3,2,3,2,3,2,1,3,2,3,2,2,2,2,5,3,6,5,5,5,6,3,3,1,1,0,1,1,0,0,1,0,1,0,0,1,1,1,1,3,2,2,2,19,2,3,10,1,10,2,1,4,2,2

,Q2A,Q4A,Q7A,Q9A,Q15A,Q19A,Q20A,Q23A,Q25A,Q28A,Q30A,Q36A,Q40A,Q41A,Extraverted-enthusiastic,Critical-quarrelsome,Dependable-self_disciplined,Anxious-easily upset,Open to new experiences-complex,Reserved-quiet,Sympathetic-warm,Disorganized-careless,Calm-emotionally_stable,Conventional-uncreative,VCL1,VCL2,VCL3,VCL4,VCL5,VCL6,VCL7,VCL8,VCL9,VCL10,VCL11,VCL12,VCL13,VCL14,VCL15,VCL16,education,urban,gender,engnat,age,screensize,hand,religion,orientation,race,voted,married,familysize,AgeGroups,Condition
0,3,3,3,1,3,2,2,3,3,2,1,3,2,3,1,5,7,7,7,7,7,5,1,1,1,0,0,1,1,0,1,0,0,1,0,0,0,1,1,1,2,3,2,2,16,1,1,12,1,10,2,1,2,1,2
1,0,2,2,2,2,0,0,0,1,3,2,2,0,1,6,5,4,7,5,4,7,7,1,5,1,1,0,1,1,0,0,0,0,1,0,0,0,1,1,1,2,3,2,1,16,2,2,7,0,70,2,1,4,1,1
2,0,0,0,1,3,1,0,1,1,0,1,3,1,0,2,5,2,2,5,6,5,5,3,2,1,0,0,1,1,0,0,0,0,0,1,0,0,1,1,1,2,3,2,2,17,2,1,4,3,60,1,1,3,2,0
3,2,0,3,2,1,0,1,0,0,0,2,0,3,3,1,1,7,4,6,4,6,1,6,1,1,0,0,1,1,0,0,0,0,1,0,0,0,1,1,1,1,3,2,1,13,2,2,4,5,70,2,1,5,1,1
4,1,3,3,3,3,3,3,3,3,3,3,3,3,3,2,5,3,6,5,5,5,6,3,3,1,1,0,1,1,0,0,1,0,1,0,0,1,1,1,1,3,2,2,2,19,2,3,10,1,10,2,1,4,2,2

,Q1A,Q6A,Q8A,Q11A,Q12A,Q14A,Q18A,Q22A,Q27A,Q29A,Q32A,Q33A,Q35A,Q39A,Extraverted-enthusiastic,Critical-quarrelsome,Dependable-self_disciplined,Anxious-easily upset,Open to new experiences-complex,Reserved-quiet,Sympathetic-warm,Disorganized-careless,Calm-emotionally_stable,Conventional-uncreative,VCL1,VCL2,VCL3,VCL4,VCL5,VCL6,VCL7,VCL8,VCL9,VCL10,VCL11,VCL12,VCL13,VCL14,VCL15,VCL16,education,urban,gender,engnat,age,screensize,hand,religion,orientation,race,voted,married,familysize,AgeGroups,Condition
0,3,3,3,3,3,3,3,3,3,3,3,1,3,3,1,5,7,7,7,7,7,5,1,1,1,0,0,1,1,0,1,0,0,1,0,0,0,1,1,1,2,3,2,2,16,1,1,12,1,10,2,1,2,1,2
1,3,3,3,1,1,3,1,2,2,2,2,2,1,1,6,5,4,7,5,4,7,7,1,5,1,1,0,1,1,0,0,0,0,1,0,0,0,1,1,1,2,3,2,1,16,2,2,7,0,70,2,1,4,1,2
2,2,2,2,1,0,0,1,2,1,1,2,0,2,1,2,5,2,2,5,6,5,5,3,2,1,0,0,1,1,0,0,0,0,0,1,0,0,1,1,1,2,3,2,2,17,2,1,4,3,60,1,1,3,2,1
3,1,2,1,1,0,3,0,0,3,2,0,1,0,2,1,1,7,4,6,4,6,1,6,1,1,0,0,1,1,0,0,0,0,1,0,0,0,1,1,1,1,3,2,1,13,2,2,4,5,70,2,1,5,1,1
4,1,1,3,1,3,3,3,2,1,1,3,3,2,2,2,5,3,6,5,5,5,6,3,3,1,1,0,1,1,0,0,1,0,1,0,0,1,1,1,1,3,2,2,2,19,2,3,10,1,10,2,1,4,2,2

In [12]:
print(data_depression['Condition'].value_counts())
print(data_anxiety['Condition'].value_counts())
print(data_stress['Condition'].value_counts())

2    20054
0    12642
1     7079
Name: Condition, dtype: int64
0    18182
2    12995
1     8598
Name: Condition, dtype: int64
2    20639
0    10569
1     8567
Name: Condition, dtype: int64

In [13]:
def ratainData(source):
    condition = {}
    for i in range(3):
        condition["source{i}"]=source.copy()
        condition["source{i}"]=condition["source{i}"][condition["source{i}"].Condition == i]
        globals()[f"final_source{i}"]=condition["source{i}"].iloc[:7000]

    final_source=pd.concat([final_source0,final_source1,final_source2])   
    final_source = final_source.sample(frac=1) 
    return final_source

final_depression=ratainData(data_depression)
final_anxiety=ratainData(data_anxiety)
final_stress=ratainData(data_stress)
display(final_depression,final_anxiety,final_stress)

,Q3A,Q5A,Q10A,Q13A,Q16A,Q17A,Q21A,Q24A,Q26A,Q31A,Q34A,Q37A,Q38A,Q42A,Extraverted-enthusiastic,Critical-quarrelsome,Dependable-self_disciplined,Anxious-easily upset,Open to new experiences-complex,Reserved-quiet,Sympathetic-warm,Disorganized-careless,Calm-emotionally_stable,Conventional-uncreative,VCL1,VCL2,VCL3,VCL4,VCL5,VCL6,VCL7,VCL8,VCL9,VCL10,VCL11,VCL12,VCL13,VCL14,VCL15,VCL16,education,urban,gender,engnat,age,screensize,hand,religion,orientation,race,voted,married,familysize,AgeGroups,Condition
13363,0,0,0,0,0,1,1,0,0,0,1,0,0,2,5,2,2,3,6,3,7,7,6,3,1,1,0,1,1,0,0,0,0,1,0,0,0,1,1,1,3,3,2,2,29,1,1,10,1,10,1,1,4,3,0
35174,1,1,1,1,2,1,1,1,2,1,1,1,1,1,0,0,0,1,0,2,0,5,0,0,1,1,0,1,0,0,0,1,0,1,0,0,0,0,1,1,3,1,2,2,21,1,1,10,4,10,2,1,5,2,1
6062,1,2,0,2,3,3,2,3,2,2,3,0,2,3,5,6,6,5,7,2,3,4,2,2,0,1,1,1,1,0,0,0,0,1,0,0,0,1,1,1,3,3,2,2,19,1,1,10,1,10,2,1,5,2,2
15734,0,0,0,0,2,0,0,1,1,0,0,0,0,0,7,3,2,3,5,3,6,5,4,5,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,1,3,0,1,13,1,2,7,1,60,2,1,3,1,0
6981,1,2,1,1,1,2,2,0,2,1,1,1,0,3,2,3,2,3,3,2,2,3,1,2,0,1,0,1,1,0,0,0,0,1,0,0,0,0,1,1,2,1,2,2,17,1,1,0,0,10,2,1,5,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1022,1,2,1,1,1,1,1,1,2,1,3,1,1,2,1,4,7,5,5,7,5,1,4,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,2,1,36,1,3,7,0,70,2,2,3,4,1
627,0,3,0,0,3,0,0,3,0,3,0,0,0,3,5,5,1,1,7,3,1,7,7,4,1,1,0,1,1,0,0,0,0,1,0,0,1,1,1,1,2,3,1,1,17,2,1,7,1,30,2,1,3,2,1
2663,2,3,3,2,3,2,2,3,3,2,1,3,2,3,5,5,1,5,6,5,5,7,5,6,1,1,1,1,1,0,1,1,0,1,1,1,1,1,1,1,3,2,1,1,44,2,1,1,1,60,2,1,4,4,2
10214,1,0,0,0,0,0,0,0,0,1,0,0,0,1,6,1,3,7,4,2,6,5,3,2,1,0,0,1,1,0,0,0,0,1,0,0,0,0,1,1,1,3,2,2,16,1,1,10,1,10,2,1,2,1,0
17173,0,0,0,1,2,1,2,0,2,1,0,1,0,1,3,2,7,4,7,3,6,3,5,4,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,3,2,1,1,20,1,1,10,2,10,2,1,6,2,0

,Q2A,Q4A,Q7A,Q9A,Q15A,Q19A,Q20A,Q23A,Q25A,Q28A,Q30A,Q36A,Q40A,Q41A,Extraverted-enthusiastic,Critical-quarrelsome,Dependable-self_disciplined,Anxious-easily upset,Open to new experiences-complex,Reserved-quiet,Sympathetic-warm,Disorganized-careless,Calm-emotionally_stable,Conventional-uncreative,VCL1,VCL2,VCL3,VCL4,VCL5,VCL6,VCL7,VCL8,VCL9,VCL10,VCL11,VCL12,VCL13,VCL14,VCL15,VCL16,education,urban,gender,engnat,age,screensize,hand,religion,orientation,race,voted,married,familysize,AgeGroups,Condition
22681,3,1,2,1,0,0,1,1,3,1,0,0,2,0,4,3,5,5,6,6,3,5,2,2,1,1,0,1,1,0,0,0,0,1,0,1,1,1,1,1,2,2,1,1,18,2,1,1,1,60,2,1,3,2,1
10418,3,0,0,1,0,1,0,0,2,1,1,0,3,0,1,6,4,7,2,6,4,4,2,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,3,1,2,2,33,1,1,8,1,10,1,2,4,3,0
10084,1,1,1,2,0,1,1,1,1,1,1,2,1,1,6,5,7,5,5,6,5,4,6,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,4,1,2,2,24,1,1,10,1,10,2,1,2,3,1
13699,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,4,6,1,6,5,3,1,6,4,1,1,0,1,0,0,0,0,0,1,0,0,0,1,1,1,3,3,2,0,19,1,1,10,0,10,0,1,4,2,0
16896,3,1,0,2,0,0,3,0,1,0,3,3,3,3,1,7,1,7,1,7,4,7,1,4,1,0,0,1,1,0,0,0,0,1,0,0,0,0,1,1,3,2,2,2,20,1,1,10,1,10,2,1,7,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2110,0,3,3,3,1,1,3,3,2,3,3,3,3,3,6,7,5,7,5,5,5,7,1,2,1,1,1,1,1,0,0,1,0,1,0,0,1,1,1,1,2,1,2,2,19,2,1,12,5,70,1,1,2,2,2
531,1,0,2,3,1,3,0,0,3,0,2,0,3,2,1,6,6,7,2,6,3,7,2,2,1,1,0,1,1,0,0,0,0,1,0,0,1,1,1,1,1,3,2,1,14,1,1,2,2,70,2,1,4,1,1
4450,1,0,0,1,0,0,0,0,1,0,0,1,0,0,5,2,6,5,5,5,6,2,6,5,1,1,0,1,1,0,0,0,0,1,0,0,0,1,1,1,3,3,2,1,36,2,1,7,1,60,1,2,1,4,0
6820,1,1,0,1,0,0,1,1,0,0,0,0,1,0,4,1,6,5,6,4,1,2,5,4,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,4,3,2,2,30,1,1,10,1,10,2,2,6,3,0
8691,0,0,1,1,1,0,2,0,1,1,2,2,2,0,4,3,6,6,5,1,4,5,4,2,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,3,1,2,1,13,1,1,10,1,10,2,1,11,1,0

,Q1A,Q6A,Q8A,Q11A,Q12A,Q14A,Q18A,Q22A,Q27A,Q29A,Q32A,Q33A,Q35A,Q39A,Extraverted-enthusiastic,Critical-quarrelsome,Dependable-self_disciplined,Anxious-easily upset,Open to new experiences-complex,Reserved-quiet,Sympathetic-warm,Disorganized-careless,Calm-emotionally_stable,Conventional-uncreative,VCL1,VCL2,VCL3,VCL4,VCL5,VCL6,VCL7,VCL8,VCL9,VCL10,VCL11,VCL12,VCL13,VCL14,VCL15,VCL16,education,urban,gender,engnat,age,screensize,hand,religion,orientation,race,voted,married,familysize,AgeGroups,Condition
5822,2,3,3,2,2,2,2,1,3,2,2,2,2,3,4,5,7,6,6,7,7,5,7,6,1,1,0,1,1,0,1,0,0,1,0,0,0,1,1,1,3,3,2,1,22,1,1,10,0,70,2,1,3,3,2
3933,2,3,3,3,1,1,1,2,2,3,1,1,1,1,6,5,3,6,6,1,5,6,2,2,1,0,1,1,1,0,1,1,0,1,0,0,0,1,1,1,2,3,2,2,20,1,1,6,1,60,1,1,2,2,2
12258,1,1,2,1,1,0,1,0,1,3,0,1,0,1,1,1,7,5,4,7,6,5,5,4,1,1,0,1,1,0,0,0,0,1,0,0,1,1,1,1,3,3,1,1,42,2,2,7,3,60,2,2,2,4,0
5656,1,1,2,1,1,1,1,1,1,1,1,1,0,1,6,4,5,3,3,2,7,1,7,5,1,1,0,1,1,0,0,0,0,1,0,0,1,1,1,1,3,3,2,1,22,1,1,6,1,10,2,1,3,3,1
12994,0,1,1,1,3,0,3,2,1,2,2,2,3,2,1,6,5,5,1,7,1,2,1,3,1,1,0,1,1,0,1,0,0,1,0,1,1,1,1,0,2,3,1,1,15,2,1,2,2,10,2,1,4,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28045,0,0,3,0,3,0,1,0,3,0,1,1,3,0,5,1,5,1,7,4,3,4,7,1,1,1,1,1,1,0,0,0,0,1,0,0,1,1,1,1,1,3,1,1,15,2,2,1,1,60,2,1,2,1,1
10937,3,2,3,2,2,2,0,2,3,2,0,2,1,3,3,5,2,7,5,7,6,5,6,6,1,1,0,1,1,0,0,0,0,1,0,0,0,1,1,1,4,1,2,2,20,2,1,4,2,70,1,1,3,2,2
5336,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,5,7,1,5,6,5,5,7,3,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,1,2,1,1,1,19,1,1,10,1,10,2,1,6,2,0
12458,2,1,3,1,1,0,2,0,2,2,2,1,2,1,2,2,3,4,5,7,7,5,6,1,1,1,0,1,1,0,0,0,0,1,0,0,1,1,1,1,2,2,1,1,20,2,1,0,1,10,2,1,2,2,1
5198,1,0,0,0,1,1,0,1,2,0,1,1,1,0,6,6,5,4,4,1,4,2,4,4,0,0,0,1,1,0,0,0,0,1,0,0,0,0,0,1,3,3,2,1,21,1,1,10,1,10,2,1,5,2,0

In [14]:
print(final_depression['Condition'].value_counts())
print(final_anxiety['Condition'].value_counts())
print(final_anxiety['Condition'].value_counts())

0    7000
1    7000
2    7000
Name: Condition, dtype: int64
1    7000
0    7000
2    7000
Name: Condition, dtype: int64
1    7000
0    7000
2    7000
Name: Condition, dtype: int64

In [25]:
display(final_depression.iloc[:16800],final_anxiety.iloc[:16800],final_stress.iloc[:16800])
print(final_depression.iloc[:16800]['Condition'].value_counts())
print(final_anxiety.iloc[:16800]['Condition'].value_counts())
print(final_stress.iloc[:16800]['Condition'].value_counts())

,Q3A,Q5A,Q10A,Q13A,Q16A,Q17A,Q21A,Q24A,Q26A,Q31A,Q34A,Q37A,Q38A,Q42A,Extraverted-enthusiastic,Critical-quarrelsome,Dependable-self_disciplined,Anxious-easily upset,Open to new experiences-complex,Reserved-quiet,Sympathetic-warm,Disorganized-careless,Calm-emotionally_stable,Conventional-uncreative,VCL1,VCL2,VCL3,VCL4,VCL5,VCL6,VCL7,VCL8,VCL9,VCL10,VCL11,VCL12,VCL13,VCL14,VCL15,VCL16,education,urban,gender,engnat,age,screensize,hand,religion,orientation,race,voted,married,familysize,AgeGroups,Condition
13363,0,0,0,0,0,1,1,0,0,0,1,0,0,2,5,2,2,3,6,3,7,7,6,3,1,1,0,1,1,0,0,0,0,1,0,0,0,1,1,1,3,3,2,2,29,1,1,10,1,10,1,1,4,3,0
35174,1,1,1,1,2,1,1,1,2,1,1,1,1,1,0,0,0,1,0,2,0,5,0,0,1,1,0,1,0,0,0,1,0,1,0,0,0,0,1,1,3,1,2,2,21,1,1,10,4,10,2,1,5,2,1
6062,1,2,0,2,3,3,2,3,2,2,3,0,2,3,5,6,6,5,7,2,3,4,2,2,0,1,1,1,1,0,0,0,0,1,0,0,0,1,1,1,3,3,2,2,19,1,1,10,1,10,2,1,5,2,2
15734,0,0,0,0,2,0,0,1,1,0,0,0,0,0,7,3,2,3,5,3,6,5,4,5,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,1,3,0,1,13,1,2,7,1,60,2,1,3,1,0
6981,1,2,1,1,1,2,2,0,2,1,1,1,0,3,2,3,2,3,3,2,2,3,1,2,0,1,0,1,1,0,0,0,0,1,0,0,0,0,1,1,2,1,2,2,17,1,1,0,0,10,2,1,5,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3187,1,3,2,3,1,3,1,3,2,2,3,2,1,2,1,2,1,6,3,7,5,3,2,3,1,0,0,1,1,0,0,0,0,1,0,0,0,1,1,1,1,1,2,2,19,2,1,1,1,60,2,1,2,2,2
12073,2,3,3,2,2,0,1,3,2,2,0,3,1,3,7,2,5,6,4,3,2,6,2,7,1,1,0,1,1,0,0,1,0,1,1,0,1,1,1,1,4,3,1,1,30,1,1,12,1,60,1,2,2,3,2
4780,1,2,2,2,1,2,2,2,3,2,1,0,2,2,4,1,7,7,5,7,7,1,5,4,1,0,0,1,0,0,0,0,0,1,0,0,0,0,1,1,3,2,2,2,23,2,1,10,4,10,2,1,5,3,2
13406,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,5,2,7,5,5,6,3,1,2,1,0,0,1,1,0,0,0,0,1,0,0,0,1,1,1,2,3,2,1,17,2,1,2,2,60,2,1,4,2,2
1363,0,3,3,3,2,2,2,1,0,1,2,2,2,0,6,1,6,7,5,5,7,6,1,4,1,0,0,1,1,0,0,0,1,1,0,0,0,0,1,1,2,3,2,1,17,1,2,10,5,10,2,1,4,2,2

,Q2A,Q4A,Q7A,Q9A,Q15A,Q19A,Q20A,Q23A,Q25A,Q28A,Q30A,Q36A,Q40A,Q41A,Extraverted-enthusiastic,Critical-quarrelsome,Dependable-self_disciplined,Anxious-easily upset,Open to new experiences-complex,Reserved-quiet,Sympathetic-warm,Disorganized-careless,Calm-emotionally_stable,Conventional-uncreative,VCL1,VCL2,VCL3,VCL4,VCL5,VCL6,VCL7,VCL8,VCL9,VCL10,VCL11,VCL12,VCL13,VCL14,VCL15,VCL16,education,urban,gender,engnat,age,screensize,hand,religion,orientation,race,voted,married,familysize,AgeGroups,Condition
22681,3,1,2,1,0,0,1,1,3,1,0,0,2,0,4,3,5,5,6,6,3,5,2,2,1,1,0,1,1,0,0,0,0,1,0,1,1,1,1,1,2,2,1,1,18,2,1,1,1,60,2,1,3,2,1
10418,3,0,0,1,0,1,0,0,2,1,1,0,3,0,1,6,4,7,2,6,4,4,2,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,3,1,2,2,33,1,1,8,1,10,1,2,4,3,0
10084,1,1,1,2,0,1,1,1,1,1,1,2,1,1,6,5,7,5,5,6,5,4,6,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,4,1,2,2,24,1,1,10,1,10,2,1,2,3,1
13699,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,4,6,1,6,5,3,1,6,4,1,1,0,1,0,0,0,0,0,1,0,0,0,1,1,1,3,3,2,0,19,1,1,10,0,10,0,1,4,2,0
16896,3,1,0,2,0,0,3,0,1,0,3,3,3,3,1,7,1,7,1,7,4,7,1,4,1,0,0,1,1,0,0,0,0,1,0,0,0,0,1,1,3,2,2,2,20,1,1,10,1,10,2,1,7,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24905,0,1,2,3,0,1,2,0,0,0,1,0,2,2,3,3,6,6,5,6,7,2,4,4,1,1,0,1,1,0,0,0,0,1,0,0,0,1,1,1,3,1,2,2,22,2,1,10,4,10,2,1,6,3,1
13813,3,1,3,3,0,1,3,0,3,3,1,1,3,1,5,7,4,7,7,7,7,1,4,1,0,1,0,0,1,0,0,0,0,1,0,0,0,0,1,1,3,1,2,2,23,2,1,10,1,70,2,1,2,3,2
26631,2,2,1,1,1,1,1,0,0,2,2,2,1,1,4,5,7,7,4,6,6,6,4,7,1,0,0,1,0,0,0,0,0,1,0,0,0,0,1,1,2,1,2,1,18,1,1,10,0,70,2,1,5,2,1
21286,3,2,3,3,1,3,1,0,0,2,3,1,3,2,6,7,5,7,6,5,5,4,3,3,1,0,0,1,0,0,0,0,0,1,0,0,0,0,1,1,4,3,2,2,27,1,1,10,5,70,2,1,5,3,2
17706,0,1,1,2,0,0,2,0,3,1,3,1,3,0,5,1,6,7,7,7,6,5,3,5,1,0,0,1,0,0,0,0,0,1,0,0,0,0,1,1,3,3,2,2,21,2,1,10,1,10,2,1,3,2,1

,Q1A,Q6A,Q8A,Q11A,Q12A,Q14A,Q18A,Q22A,Q27A,Q29A,Q32A,Q33A,Q35A,Q39A,Extraverted-enthusiastic,Critical-quarrelsome,Dependable-self_disciplined,Anxious-easily upset,Open to new experiences-complex,Reserved-quiet,Sympathetic-warm,Disorganized-careless,Calm-emotionally_stable,Conventional-uncreative,VCL1,VCL2,VCL3,VCL4,VCL5,VCL6,VCL7,VCL8,VCL9,VCL10,VCL11,VCL12,VCL13,VCL14,VCL15,VCL16,education,urban,gender,engnat,age,screensize,hand,religion,orientation,race,voted,married,familysize,AgeGroups,Condition
5822,2,3,3,2,2,2,2,1,3,2,2,2,2,3,4,5,7,6,6,7,7,5,7,6,1,1,0,1,1,0,1,0,0,1,0,0,0,1,1,1,3,3,2,1,22,1,1,10,0,70,2,1,3,3,2
3933,2,3,3,3,1,1,1,2,2,3,1,1,1,1,6,5,3,6,6,1,5,6,2,2,1,0,1,1,1,0,1,1,0,1,0,0,0,1,1,1,2,3,2,2,20,1,1,6,1,60,1,1,2,2,2
12258,1,1,2,1,1,0,1,0,1,3,0,1,0,1,1,1,7,5,4,7,6,5,5,4,1,1,0,1,1,0,0,0,0,1,0,0,1,1,1,1,3,3,1,1,42,2,2,7,3,60,2,2,2,4,0
5656,1,1,2,1,1,1,1,1,1,1,1,1,0,1,6,4,5,3,3,2,7,1,7,5,1,1,0,1,1,0,0,0,0,1,0,0,1,1,1,1,3,3,2,1,22,1,1,6,1,10,2,1,3,3,1
12994,0,1,1,1,3,0,3,2,1,2,2,2,3,2,1,6,5,5,1,7,1,2,1,3,1,1,0,1,1,0,1,0,0,1,0,1,1,1,1,0,2,3,1,1,15,2,1,2,2,10,2,1,4,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24757,1,0,1,1,2,2,1,1,1,2,0,2,1,1,3,2,3,7,7,6,6,6,3,6,1,1,0,1,1,0,0,1,0,1,0,0,1,1,1,1,3,3,1,1,22,2,1,1,1,60,2,1,2,3,1
25297,1,0,0,1,0,2,1,0,2,1,1,1,1,1,1,5,6,2,7,5,6,2,5,6,1,1,0,1,1,0,0,0,0,1,0,1,0,0,1,1,3,2,2,2,25,2,1,10,0,10,1,1,4,3,0
31737,1,2,3,1,2,1,2,0,2,0,0,2,0,1,4,1,5,5,5,7,2,4,2,5,1,1,0,1,1,0,0,0,0,1,0,0,1,1,1,1,2,3,1,2,22,2,1,0,1,60,1,1,2,3,1
15066,0,1,1,1,1,2,1,2,1,0,0,2,0,2,4,5,5,5,3,6,5,4,5,3,1,1,0,1,0,0,0,0,0,1,0,0,1,1,1,1,2,3,2,2,20,1,1,1,2,60,1,1,0,2,1
24299,1,1,1,1,0,1,1,0,1,1,1,0,1,1,6,7,7,5,6,5,7,4,6,4,1,1,0,1,1,0,0,1,1,1,0,1,0,0,1,1,4,3,2,2,32,1,1,10,0,10,1,2,1,3,0

2    5634
1    5591
0    5575
Name: Condition, dtype: int64
1    5649
0    5585
2    5566
Name: Condition, dtype: int64
1    5623
0    5598
2    5579
Name: Condition, dtype: int64

In [20]:
final_depression.iloc[:16800].to_csv('data_train_depr.csv', index = False)
final_depression.iloc[-4200:].to_csv('data_valid_depr.csv', index = False)

final_anxiety.iloc[:16800].to_csv('data_train_anx.csv', index = False)
final_anxiety.iloc[-4200:].to_csv('data_valid_anx.csv', index = False)

final_stress.iloc[:16800].to_csv('data_train_str.csv', index = False)
final_stress.iloc[-4200:].to_csv('data_valid_str.csv', index = False)